# site settings
title: RKMOBI.cz
subtitle: RK Mobi cz
email: krestynradim@gmail.com
description: Ohřevné teplodrátěné koše, ochrana rostlin před mrazem – výroba a prodej.
baseurl: "" # for direct root domain usage
url: # Fill if custom domain, e.g. https://www.rkmobi.cz
author:
street_address: Drušstevní 276/15
city: Mohelnice
state: 
zip_code: 789 85
country: Česká republika
phone: +420 776 071 283

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
